export { default as About } from './About';
export { default as Company } from './Company'
export { default as Worksites } from './Worksites'
export { default as AddWorksite } from './AddWorksite'
export { default as Landing } from './Landing'
export { default as Register } from './Register'
export { default as AdminRegister } from './AdminRegister'
export { default as Login } from './Login'
export { default as HomeLayout } from './HomeLayout'
export { default as Error } from './Error'
export { default as SingleWorksite } from './SingleWorksite'
export { default as Profile } from './Profile'
export { default as Changepassword } from './Changepassword'
export { default as Pricing } from './Pricing'
export {default as Privacypolicy} from './privacypolicy'
export {default as TAC} from './TAC'
export {default as ForgotPassword} from './ForgotPassword'
export {default as ResetPassword} from './ResetPassword'
